
type Usuario {
    id: Int!
    nombreUsuario: String!
    email: String!
    contrasena: String!
    fechaCreacion: String!
    imgURL: String
    activo: Boolean!
    temaOscuro: Boolean!
}

type ResponseMsg {
    STATUS: Int
    message: String
    data: Usuario
    token: String
}

extend type Query {
    usuarios: [Usuario!]!
    usuario(id: Int!): Usuario
    Login(email: String!, password: String!): ResponseMsg
    RegisterUser(nombreUsuario: String!, email: String!, password: String!): ResponseMsg

}